### ISSUE TITLE
Create common format for old data

### ISSUE THREAD

**Issue by kevinprince** [geeksoflondon/hamster#14]
We should standardize the data for import.

**Comment by cbetta** [comment]
What do you mean with this?

**Comment by cbetta** [comment]
Closing this until @kevinprince explains what it means

**Comment by kevinprince** [comment]
We need to come up with how we are going to get BCL6 through 9  + other events data into hamster including things like attendance.

**Comment by cbetta** [comment]
Yes, see https://github.com/geeksoflondon/hamster/issues/11, closing again
