### ISSUE TITLE
Add Events API

### ISSUE THREAD

**Issue by kevinprince** [geeksoflondon/hamster#15]
We need to store events in hamster.

**Comment by kevinprince** [comment]
Should store the following:

``` ruby
{
:name => 'BarCamp London',
:start => '2012-06-01 10:00',
:end => '2012-06-2 16:00',
:eventbrite_xid => 'EB392033',
:url => 'http://barcamplondon.org'
}
```

Relates to

``` ruby
has_many :tickets
has_one :venue
```

**Comment by kevinprince** [comment]
Not sure how we should store images.

**Comment by cbetta** [comment]
1. Forget about images for now
2. Rename `event_url` to `url`
3. Move venue into own model with `id`, `name`, `url`
4. I prefer `xid` for any external IDs (also, what is that, eventbrite ID? Might be better to just call it `eventbrite_xid` then)
5. It does not have many `attendees`. It has many `tickets` and a ticket is a relation between an `attendee` and an `event`. Don't model this yet though.
6. Worth storing if it's an all-day one?

**Comment by kevinprince** [comment]
1. Will ignore for now
2. Done
3. Created ticket
4. Changed
5. Fixed
6. Can be calculated from the dates? (event.is_one_day? as a method)

**Comment by cbetta** [comment]
Re 6, not sure. It's more for display purposes. As in: do we want to show June 8th 8am - June 9th 5pm, or just June 8th-June 9th

**Comment by kevinprince** [comment]
I think that is a decorator in a helper later.

**Comment by cbetta** [comment]
Maybe. Let's see and start without
