### ISSUE TITLE
Add venue api

### ISSUE THREAD

**Issue by kevinprince** [geeksoflondon/hamster#17]

**Comment by kevinprince** [comment]
Needs id, venue, name

**Comment by cbetta** [comment]
Renamed title of ticket. You had "ticket api"

**Comment by cbetta** [comment]
Ticket api issue is here https://github.com/geeksoflondon/hamster/issues/2

**Comment by cbetta** [comment]
Also, needs `name`, `url`, maybe `address`

**Comment by cbetta** [comment]
This is closed right?

**Comment by cbetta** [comment]
Ah no it isn't ignore me
