### ISSUE TITLE
Defining language for registration 

### ISSUE THREAD

**Issue by kevinprince** [geeksoflondon/hamster#33]
Following on discussion with @mseckington we need to define the language we use for defining attendee state. 

Currently these are:

```
- *attending*  attendee is either confirmed or still unconfirmed
- *attended* attendee has arrived at the event
- *on-site* attendee is in the venue
- *off-site* attendee is out of the venue
- *confirmed* attendee has confirmed they are attending via retain
- *unconfirmed* attendee has not confirmed they are attending via retain
- *cancelled* attendee has cancelled their ticket via retain
```

We need some proposals for making this language clearer.

**Comment by kevinprince** [comment]
Proposal: 
- Coming 
- Arrived
- On-Site
- Off-Site
- Confirmed
- Unconfirmed
- Cancelled

**Comment by kevinprince** [comment]
Thoughts @mseckington

**Comment by mseckington** [comment]
I'd suggest "Expected" and "Showed Up" for the first 2. Fine with the rest.

I'm wondering though should we also have something like "Not coming back"

**Comment by kevinprince** [comment]
I like the idea of not coming back. Just add it as a button on the checkout screen?
