### ISSUE TITLE
Add admin authentication 

### ISSUE THREAD

**Issue by cbetta** [geeksoflondon/hamster#6]
Just an idea. Allow for any other app to use hamster as its authentication endpoint would be nice.

**Comment by kevinprince** [comment]
as a thought for general GoL ACL, why not use github oAuth?

**Comment by cbetta** [comment]
Makes sense, but we might need some way to administer which GH accounts have access to what... Will give it a think

**Comment by kevinprince** [comment]
Use teams?

**Comment by cbetta** [comment]
Sounds good. Might need to add that into a module somehow still. Let's keep this ticket open for now.

**Comment by cbetta** [comment]
I think I agree that we don't need any user auth in here, instead we handle it in the seperate apps.
